### ISSUE TITLE
dash does not know about the pipefail option

### ISSUE THREAD

**Issue by gerryd** [FOSDEM/infrastructure#224]
We have the `pipefail` option set in a few places. However, on modern Debian systems, `/bin/sh` is dash, which does not know `pipefail`.

  - ansible/playbooks/roles/video-box/tasks/configure_ssd.yml
  - playbooks/roles/video-stream-dump/tasks/configure_hdd.yml
  - playbooks/roles/video-streamer-backend/tasks/mount_ssd.yml

Adding the following helps:

      args:
        executable: /bin/bash

But then there is another problem, full example from `configure_ssd.yml`:

    - name: detect existing partitions on the SSD
      shell: |
        set -o pipefail
        fdisk -l {{ ssd_drive }} | grep ^\/ | wc -l
      register: number_of_partitions
      changed_when: false

If there are no partitions, this will always fail, as `grep` will return with rc 1. Adding `|| true` after `grep` would fix it, but sort of voids the point of using `pipefail`?

Suggestions?

**Comment by SuperQ** [comment]
I was thinking about how to refactor these anyway. I wanted to switch to a normal partition setup, since it's easier to detect and manage the filesystem if there's `/dev/sdX1`, rather than a formatting and mounting a bare block device.

In the mean time, we could either switch the execution to bash with this:

```yaml
shell: ...
args:
  executable: /bin/bash
```

Or I can just revert the pipefail test and add a `noqa` flag.

What do you think?

**Comment by SuperQ** [comment]
Posted a rollback PR.

**Comment by SuperQ** [comment]
One way to avoid the pipefail issue, is to not pipe.

```yaml
ssd_device: sdb

shell: "awk '{if($4 ~ /^{{ ssd_device }}/) c += 1} END {print c}' /proc/partitions"
```

**Comment by krokodilerian** [comment]
I think all the "lovely" tools out there check the existence of partitions by looking for /dev/sda[0-9]+ and count those. It's pretty much insane, but doesn't seem to be a better way (there's something similar in /sys/class/block/sda/sda[0-9]+).

My suggestion would be to do:
blockdev --rereadpt device
udevadm settle
list /dev/sd...
and count them in ansible as the count

that would solve the exact task at hand. In short, partitions are crap.

As for partitioning at all, I can't remember the reason for dropping them,  but my recent experience in this regard is that we very much want a GPT or msdos label, and a single partition, instead of the raw device - turns out that there's code in the linux kernel that detects partitions in raw devices based on a few bytes here and there, and we've seen them being triggered by some data.

**Comment by SuperQ** [comment]
:+1: to putting a GPT label on the block device.

**Comment by yoe** [comment]
I know I'm late to the party, but...

> If there are no partitions, this will always fail, as `grep` will return with rc 1. Adding `|| true` after `grep` would fix it, but sort of voids the point of using `pipefail`?

You can work around that by testing the exit state:

`foo | bar | { grep foo || test $? -eq 1 }`

According to the docs, the exit state of "grep" is 1 when no lines matched, and could have other exit states in other cases. Since we don't consider "no lines matched" to be an error, we test for that exact error from grep only, and ignore it -- in all other cases, we don't, and then `pipefail` still applies.
